version: "2"
services:
  web:
    container_name: web_api
    build: .
    environment:
      NODE_ENV: production
    command: pm2-docker processes.json
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo_web
    image: mongo
    volumes:
      - ./.Docker/mongodb/db:/data/db
    ports:
      - "27017:27017"

    nginx:
      image: nginx
      ports:
          - "80:80"
      volumes:
          - ./dripdraft.conf:/etc/nginx/conf.d/default
      command: /bin/bash -c "echo -e 'upstream backend { server web:3000; }\nserver { listen 80; location / { proxy_pass http://backend; }}' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
      links:
          - web

volumes:
    mongo_web:

